[workspace]
resolver = "3"
members = ["core", "clients/rust", "ffi", "clients/python", "proto", "bench", "codegen"]

[workspace.lints.rust]
missing_debug_implementations = "deny"

[workspace.lints.clippy]
redundant_clone = "deny"
needless_collect = "deny"
large_enum_variant = "deny"

[profile.release]
lto = "fat"
codegen-units = 1
