[package]
name = "tarwyn_python"
version = "0.1.0"
edition = "2024"
description = "Python bindings for the tarwyn client."
license = "MIT"
publish = false

[lib]
test = false
doctest = false
name = "tarwyn"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py39", "multiple-pymethods"] }
tarwyn_client = { path = "../rust" }
tarwyn_protobuf = { path = "../../proto", version = "0.1.0" }
