[versions]
wpilib = "2027.0.0-alpha-7"
wpilib-bench = "2025.3.2"
junit = "5.11.4"
junit-platform = "1.11.4"
jackson = "2.19.2"
quickbuf = "1.3.3"
tarwyn-jar = "v5.0.0"

[libraries]
wpilib-wpiutil = { module = "org.wpilib.wpiutil:wpiutil-java", version.ref = "wpilib" }
wpilib-wpimath = { module = "org.wpilib.wpimath:wpimath-java", version.ref = "wpilib" }
wpilib-wpiunits = { module = "org.wpilib.wpiunits:wpiunits-java", version.ref = "wpilib" }
wpilib-bench-ntcore = { module = "edu.wpi.first.ntcore:ntcore-java", version.ref = "wpilib-bench" }
wpilib-bench-wpiutil = { module = "edu.wpi.first.wpiutil:wpiutil-java", version.ref = "wpilib-bench" }
wpilib-bench-ntcore-jni = { module = "edu.wpi.first.ntcore:ntcore-jni", version.ref = "wpilib-bench" }
wpilib-bench-wpiutil-jni = { module = "edu.wpi.first.wpiutil:wpiutil-jni", version.ref = "wpilib-bench" }
tarwyn = { module = "org.team488:TARWYN", version.ref = "tarwyn-jar" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
quickbuf = { module = "us.hebi.quickbuf:quickbuf-runtime", version.ref = "quickbuf" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
