[package]
name = "tarwyn_server"
version = "0.0.3"
edition = "2024"
description = "A Rust server for managing tarwyn over ZeroMQ."

[dependencies]
zmq = "0.10.0"
prost = "0.14.1"
clap = { version = "4.5.47", features = ["derive"] }
log = { version = "0.4.28", features = ["std"] }
arc-swap = "1.7"
tarwyn_protobuf = { path = "../proto", version = "0.0.3" }
