//! The tarwyn wire format: [`protobuf`] messages, the [`telemetry`] datagram,
//! and the [`wpilog`] file writer.
//!
//! The protobuf code is generated by [`protox`](https://crates.io/crates/protox),
//! so a build needs no `protoc`.

#![warn(missing_docs)]

/// Message types generated from `proto/messages.proto`.
#[expect(
    missing_docs,
    reason = "prost generates these; messages.proto carries no comments"
)]
pub mod protobuf {
    include!(concat!(env!("OUT_DIR"), "/protobuf.rs"));
}

/// The UDP datagram format carrying the telemetry plane.
pub mod telemetry;
/// A WPILOG writer, and the background logger built on it.
pub mod wpilog;
